#:include kv/homescreen.kv
#:include kv/settingsscreen.kv
#: import ScreenManager kivy.uix.screenmanager.ScreenManager
#: import Screen kivy.uix.screenmanager.ScreenManager
#: import SettingsScreen screen

GridLayout:
   cols:1
   ScreenManager:
      id: screen_manager
      HomeScreen:
         name:"home_screen"
         id:home_screen
      SettingsScreen:
         name:"settings_screen"
         id:"settings_screen"